# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentwatch < Formula
  desc "Terminal UI for watching AI agents work"
  homepage "https://github.com/twiced-technology-gmbh/agentwatch"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.1.1/agentwatch_0.1.1_darwin_amd64.tar.gz"
      sha256 "d8a3676d7d1aff9142cf75ed6e1a1d5cc3aa2983a925cca05d02425b19b9771e"

      def install
        bin.install "agentwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.1.1/agentwatch_0.1.1_darwin_arm64.tar.gz"
      sha256 "33d3ce8f92ed7a64109639828d3a4cfd2243e0fd06e2060617f3036c1d2b0e2f"

      def install
        bin.install "agentwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.1.1/agentwatch_0.1.1_linux_amd64.tar.gz"
      sha256 "934b0a944e7b999c3768df7f437240300f9fa674bf5ded0b57f74515bcf9e0fa"
      def install
        bin.install "agentwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.1.1/agentwatch_0.1.1_linux_arm64.tar.gz"
      sha256 "b5feacef09a23211b88f601895848f6e44518d80a7564ac691302a3b8d7d6251"
      def install
        bin.install "agentwatch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentwatch --version")
  end
end
