# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentwatch < Formula
  desc "Terminal UI for watching AI agents work"
  homepage "https://github.com/twiced-technology-gmbh/agentwatch"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.3.2/agentwatch_0.3.2_darwin_amd64.tar.gz"
      sha256 "c6d529ac277361ae121ec49545f67670d09df6d8d2bd44e737eb12a0b386c066"

      def install
        bin.install "agentwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.3.2/agentwatch_0.3.2_darwin_arm64.tar.gz"
      sha256 "5c50b65fa23cb0b58b4f6e4cae7cb1713b90c54b4f3c874f63778d8245f78638"

      def install
        bin.install "agentwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.3.2/agentwatch_0.3.2_linux_amd64.tar.gz"
      sha256 "f3fb0aac13823cb7452a9bc1d64ad2753ad12e88aab40fbfc0efb84a626eb041"
      def install
        bin.install "agentwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twiced-technology-gmbh/agentwatch/releases/download/v0.3.2/agentwatch_0.3.2_linux_arm64.tar.gz"
      sha256 "1689dfe5abbe1c267628cababec076e9859c4096386f3f02dc5d331ab45df5fe"
      def install
        bin.install "agentwatch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentwatch --version")
  end
end
